 [functions.create-asaas-subaccount]
 verify_jwt = false
project_id = "lktzrqjvqoojlrhqnxuz"

[functions.zapi-webhook]
verify_jwt = false

[functions.zapi-send-internal]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.confirm-order-payment]
verify_jwt = false