project_id = "lktzrqjvqoojlrhqnxuz"

[functions.create-asaas-subaccount]
verify_jwt = false

[functions.zapi-webhook]
verify_jwt = false

[functions.zapi-send-internal]
verify_jwt = false

[functions.asaas-webhook]
verify_jwt = false

[functions.confirm-order-payment]
verify_jwt = false

[functions.monthly-billing]
verify_jwt = false

[functions.auto-withdraw-subaccounts]
verify_jwt = false

[functions.asaas-financial-panel]
verify_jwt = false

[functions.evolution-webhook]
verify_jwt = false

[functions.evolution-send-message]
verify_jwt = false